### ISSUE TITLE
KinD API Audit

### ISSUE THREAD

**Issue by mchirico** [mchirico/agil#54]
```yaml
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      audit-policy-file: "/auditing/basic-policy.yaml"
      audit-log-path: "/auditing/audit.log"
    extraVolumes:
    - name: "auditing"
      hostPath: "/auditing"
      mountPath: "/auditing"
      readOnly: false
      pathType: "Directory"
nodes:
- role: control-plane
  # add a mount from /path/to/my/files on the host to /files on the node
  extraMounts:
  - hostPath: /home/ubuntu/auditing/
    containerPath: /auditing
    propagation: None

```
![image](https://user-images.githubusercontent.com/755710/102775429-d5527280-435a-11eb-9e12-379baca00866.png)
